PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = tm-qpr3

NIGHTSHADE_BUILD_DATE := $(shell date -u +%Y%m%d)
TARGET_PRODUCT_SHORT := $(subst nightshade_,,$(NIGHTSHADE_BUILD))

ifeq ($(IS_OFFICIAL), true)
 NIGHTSHADE_BUILDTYPE := OFFICIAL
else
 NIGHTSHADE_BUILDTYPE := COMMUNITY
endif

# Internal version
NIGHTSHADE_VERSION := $(PRODUCT_VERSION_MAJOR)-$(NIGHTSHADE_BUILDTYPE)-$(NIGHTSHADE_BUILD_DATE)

# Display version
NIGHTSHADE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(PRODUCT_VERSION_MINOR)
